fix

diff --git a/OLX_Dyplom_ADM/Jenkins/Jenkinsfile.build b/OLX_Dyplom_ADM/Jenkins/Jenkinsfile.build
--- a/OLX_Dyplom_ADM/Jenkins/Jenkinsfile.build
+++ b/OLX_Dyplom_ADM/Jenkins/Jenkinsfile.build
@@ -104,20 +104,13 @@ pipeline {
         success {
             echo '🎉 Pipeline completed successfully!'
         }
-        failure {
-            echo '💥 Pipeline failed'
-            sh 'docker compose -f docker-compose.yml down || true'
-            sh '''
-                docker system prune -f
-                docker volume prune -f
-            '''
-        }
-        always {
-            script {
-                archiveArtifacts artifacts: '*.log', 
-                    fingerprint: true
-                //cleanWs()
-            }
-        }
+        // failure {
+        //     echo '💥 Pipeline failed'
+        //     sh 'docker compose -f docker-compose.yml down || true'
+        //     sh '''
+        //         docker system prune -f
+        //         docker volume prune -f
+        //     '''
+        // }
     }
 }
